services:
  app:
    image: ghcr.io/teamnyl/teacharlie:latest
    env_file:
      - stack.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  migrate:
    image: ghcr.io/teamnyl/teacharlie:latest
    env_file:
      - stack.env
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: ghcr.io/teamnyl/teacharlie:latest
    env_file:
      - stack.env
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - stack.env
    ports:
      - "5432:5432"
